spring:
  application:
    name: SCW-USER
  datasource:
    username: root
    password: yj417.
    url: jdbc:mysql://116.62.26.47:3306/atcrowdfunding?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 116.62.26.47
    port: 6379
    
mybatis: 
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://116.62.26.47:8761/eureka/
  instance:
    appname: SCW-USER
    prefer-ip-address: true

server:
  port: 7000
  
swagger2:
  enable: true