spring:
  application:
    name: SCW-ORDER
  datasource:
    username: root
    password: yj417.
    url: jdbc:mysql://localhost:3306/atcrowdfunding?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.154.130
    port: 6379


feign:
  hystrix:
    enabled: true
    
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #appname: ORDER
    prefer-ip-address: true
    
    
server:
  port: 9000
  
swagger2:
  enable: true


  

    
  